### ISSUE TITLE
UI is a bit confusing?

### ISSUE THREAD

**Issue by noonien** [cdepillabout/nix-query-tree-viewer#12]
when running
```
$ nix-query-tree-viewer <store-path>
```

The UI starts, and is showing a tree of all dependencies.
If one wishes to search through the dependencies, using the search tool, the results are not as expected IMHO.

Instead of searching through the dependencies of the current tree, an error is displayed on the bottom
```
Error running `nix-store --query --tree <search term>
```
My guess the search tool actually searches through the nix store, instead of the opened tree.

Is there a way to search in the opened tree?

I want to find why the build process of a package has certain dependencies, and the tree is huge. Having no tool to search through it makes the task impossible using this utility, `nix-tree` and `nix-shell --query --tree` are not of much help either.

**Comment by cdepillabout** [comment]
I completely agree with this.

I realized this after using `nix-query-tree-viewer` for a while, but I never ended up going back and implementing search functionality.  I did create an issue about it though: #1.

I'll close this issue as a duplicate, but if you'd be interested in implementing this functionality, I'd definitely appreciate a PR!
