### ISSUE TITLE
Extract the nix-store parsing as a separate lib

### ISSUE THREAD

**Issue by baloo** [cdepillabout/nix-query-tree-viewer#8]
Hello @cdepillabout !
Thanks a lot for your work!

I'd like to reuse your library that parses `nix-store --query` output in another project. Would you think it'd be possible to extract that as a separate crate?

Here is my extract/usecase of it:
https://github.com/baloo/laurn/tree/master/crates/nixstore

Thank you!

**Comment by cdepillabout** [comment]
@baloo Did you mean to close this?

If you wanted to send a PR separating the `nix-store --query --tree` parsing into a separate directory, I'd be happy to release that as a standalone crate.

**Comment by baloo** [comment]
I meant to close this as I replaced the implementation in the end (just forgot I did that when I published my lib^^).

I dont need the tree feature in the end and the list of requirements was enough for me.
